name: Backend CI

on:
   push:
    branches: [ main ]
    paths:
      - 'novi-devops-eindopdracht.Server/**'
      - '.github/workflows/backend.yml'
   pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Run tests
        run: dotnet test Tests/Tests.csproj --no-restore --verbosity normal
        
  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        working-directory: novi-devops-eindopdracht.Server
        run: |
          docker build -t ghcr.io/${{ github.repository }}/backend:${{ github.sha }} .
          docker tag ghcr.io/${{ github.repository }}/backend:${{ github.sha }} ghcr.io/${{ github.repository }}/backend:latest

      - name: Save image
        run: |
          docker save ghcr.io/${{ github.repository }}/backend:${{ github.sha }} ghcr.io/${{ github.repository }}/backend:latest > image.tar
      - uses: actions/upload-artifact@v4
        with:
          name: docker-image-backend
          path: image.tar

  push:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - name: Download image
        uses: actions/download-artifact@v4
        with:
          name: docker-image-backend

      - name: Load image
        run: docker load < image.tar

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image to GHCR
        run: |
          docker push ghcr.io/${{ github.repository }}/backend:${{ github.sha }}
          docker push ghcr.io/${{ github.repository }}/backend:latest
